[tool.black]
line-length = 100
target-version = ["py313"]

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true

[tool.ruff]
include = ["setup.py", "scrapli/**.py", "tests/**.py"]
line-length = 100

[tool.ruff.lint]
select = [
    "FIX",
    "D",
    "PL",
    "ERA",
    "C90",
    "N",
    "PERF",
    "E",
    "W",
    "D",
    "F",
    "UP",
    "FURB",
    "RUF",
]
ignore = [
    "D105",  # Missing docstring in magic method
    "D107",  # Missing docstring in `__init__`
    "D212",  # Multi-line docstring summary should start at the first line
    "D415",  # First line should end with a period, question mark, or exclamation point
    "N818",  # Exception name `foo` should be named with an Error suffix
    "UP015", # Unnecessary mode argument
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/**.py" = ["D", "PLR0913"]
