---
name: lint

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: load env vars for workflow run
        run: |
          source .github/vars.env
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> "$GITHUB_ENV"
          echo "GO_VERSION=$GO_VERSION" >> "$GITHUB_ENV"
          echo "GCI_VERSION=$GCI_VERSION" >> "$GITHUB_ENV"
          echo "GOFUMPT_VERSION=$GOFUMPT_VERSION" >> "$GITHUB_ENV"
          echo "GOLINES_VERSION=$GOLINES_VERSION" >> "$GITHUB_ENV"

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install python dev tools
        run: |
          python -m pip install -r requirements-dev.txt

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: install go lint tools
        run: |
          go install mvdan.cc/gofumpt@${{ env.GOFUMPT_VERSION }}
          go install github.com/daixiang0/gci@${{ env.GCI_VERSION }}
          go install github.com/segmentio/golines@${{ env.GOLINES_VERSION }}

      - name: run the linters
        run: |
          make lint
